CREATE TABLE "properties" (
	"id" text PRIMARY KEY NOT NULL,
	"organization_id" text NOT NULL,
	"title" text NOT NULL,
	"description" text NOT NULL,
	"short_description" text,
	"type" text NOT NULL,
	"operation_type" text NOT NULL,
	"status" text DEFAULT 'borrador' NOT NULL,
	"price_amount" real NOT NULL,
	"price_currency" text NOT NULL,
	"negotiable" boolean DEFAULT false NOT NULL,
	"expenses_amount" real,
	"expenses_currency" text,
	"address_street" text NOT NULL,
	"address_number" text,
	"address_floor" text,
	"address_apartment" text,
	"address_city" text NOT NULL,
	"address_state" text NOT NULL,
	"address_country" text NOT NULL,
	"address_neighborhood" text,
	"address_lat" real,
	"address_lng" real,
	"address_google_maps_url" text,
	"total_area_value" real,
	"total_area_unit" text,
	"covered_area_value" real,
	"covered_area_unit" text,
	"rooms" integer,
	"bedrooms" integer,
	"bathrooms" integer,
	"garages" integer,
	"age" integer,
	"condition" text,
	"orientation" text,
	"amenities" text[] DEFAULT '{}' NOT NULL,
	"hide_exact_location" boolean DEFAULT true NOT NULL,
	"photos" text[] DEFAULT '{}' NOT NULL,
	"video_url" text,
	"virtual_tour_url" text,
	"blueprints" text[] DEFAULT '{}' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
