import type { Property, PropertyFormData } from "@/features/properties/domain/property.entity"

export function propertyToFormData(property: Property): PropertyFormData {
  return {
    title: property.title,
    description: property.description,
    shortDescription: property.shortDescription || "",
    type: property.type,
    operationType: property.operationType,
    price: property.price.amount,
    currency: property.price.currency,
    negotiable: property.negotiable,
    expenses: property.expenses?.amount ?? "",
    expensesCurrency: property.expenses?.currency ?? "USD",
    country: property.address.country,
    state: property.address.state,
    city: property.address.city,
    neighborhood: property.address.neighborhood || "",
    street: property.address.street,
    number: property.address.number || "",
    floor: property.address.floor || "",
    apartment: property.address.apartment || "",
    googleMapsUrl: property.address.googleMapsUrl || "",
    lat: property.address.lat?.toString() || "",
    lng: property.address.lng?.toString() || "",
    totalArea: property.totalArea?.value ?? "",
    coveredArea: property.coveredArea?.value ?? "",
    surfaceUnit: property.totalArea?.unit || property.coveredArea?.unit || "m2",
    rooms: property.rooms ?? "",
    bedrooms: property.bedrooms ?? "",
    bathrooms: property.bathrooms ?? "",
    garages: property.garages ?? "",
    age: property.age ?? "",
    condition: property.condition || "",
    orientation: property.orientation || "",
    amenities: property.amenities,
    hideExactLocation: property.hideExactLocation,
    photos: property.media.photos,
    videoUrl: property.media.videoUrl || "",
    virtualTourUrl: property.media.virtualTourUrl || "",
    blueprints: property.media.blueprints,
  }
}
